<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>DevelopmentChallenge.Console</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevelopmentChallenge.Data\DevelopmentChallenge.Data.csproj" />
  </ItemGroup>

</Project>
